apiVersion: apps/v1
kind: Deployment
metadata:
  name: brother
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brother
  template:
    metadata:
      labels:
        app: brother
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: brother
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7390c3e5-507f-401d-80aa-e93222e51dbb"
        - name: Vless_Path
          value: "/vlbeyb"
        - name: Vmess_UUID
          value: "43defd4c-d496-40f1-b1dc-37025402ebb6"
        - name: Vmess_Path
          value: "/vmdydb"
        - name: Share_Path
          value: "/v2link"
